<div class="page-actions">
    <div class="page-actions-inner">
        <div class="page-actions-buttons">
            <button
                class="action-primary"
                title="<?php echo __('Primary button') ?>">
               Save
            </button>
            <a href="../movie">
            <button
                class="action-secondary back"
                title="<?php echo __('Back') ?>">
                <?php echo __('Back') ?>
            </button></a>
        </div>
    </div>
</div>