<?php

?>

<style>
    table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
    td, th {  border: 1px solid black;  text-align: left;  padding: 8px;  }
    th { background-color: #dddddd; }
    .post-id{width:2%} .post-name{width:30%}

</style>
<h2>Table Director</h2>

<table>
    <tr>
        <th class="post-id">Id</th>
        <th class="post-name">Name Director</th>


    </tr>
    <?php
    foreach ($block->getDirectorCollection() as $key=>$director){
        echo '<tr>
                    <td>'.$director->getDirectorId().'</td>
                    <td>'.$director->getname().'</td>
               
                  </tr>';
    }
    ?>
</table>
