<?php

?>
<style>
    table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
    td, th {  border: 1px solid black;  text-align: left;  padding: 8px;  }
    th { background-color: #dddddd; }
    .post-id{width:2%} .post-name{width:30%}
</style>
<h2>Table Movie</h2>

<table>
    <tr>
        <th class="post-id">Id</th>
        <th class="post-name">Name Movie</th>
        <th class="post-name">Description Movie</th>
        <th class="post-name">Rating Movie</th>
        <th class="post-name">Director Movie</th>
    </tr>
    <?php
    foreach ($block->getMovieCollection() as $key=>$movie){
        echo '<tr>
                    <td>'.$movie->getMovieId().'</td>
                    <td>'.$movie->getname().'</td>
                    <td>'.$movie->getDescription().'</td>
                    <td>'.$movie->getrating().'</td>
                    <td>'.$movie->getdirector_id().'</td>
                  </tr>';
    }
    ?>
</table>
