<div class="col-m-12">
    <fieldset class="fieldset admin__fieldset " id="theme">

        <div class="admin__field field ">
            <label class="label admin__field-label" for="test_input">
                <span>Name Movie</span></label>
            <div class="admin__field-control control">
                <input name="design[test_input]" id="test_input"
                       value="" title="Test input" type="text" class="input-textadmin__control-text" />
            </div>
        </div>
        <div class="admin__field field ">
            <label class="label admin__field-label" for="test_input">
                <span>Description</span></label>
            <div class="admin__field-control control">
                <input name="design[test_input]" id="test_input"
                       value="" title="Test input" type="text" class="input-textadmin__control-text" />
            </div>

        </div>
        <div class="admin__field field ">
            <label class="label admin__field-label" for="test_input">
                <span>Rating</span></label>
            <div class="admin__field-control control">
                <input name="design[test_input]" id="test_input"
                       value="" title="Test input" type="number"  min="1" max="10" class="input-textadmin__control-text" />
            </div>
        </div>
        <div class="admin__field field ">
            <label class="label admin__field-label" for="test_input">
                <span>Director ID</span></label>
            <div class="admin__field-control control">
                <input name="design[test_input]" id="test_input"
                       value="" title="Test input" type="number"  min="1"  class="input-textadmin__control-text" />
            </div>
        </div>
    </fieldset>
</div>
